In [1]:
import pandas as pd

# Pandas loc & iloc1

In [2]:
data = pd.read_csv('matches.csv')

In [3]:
data.head()

,id,date,season,city,team1,team2,toss_winner,toss_decision,result,dl_applied,winner
0,1.0,Yes,2017,Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0.0,Sunrisers Hyderabad
1,2.0,Yes,2017,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0.0,Rising Pune Supergiant
2,3.0,Yes,2017,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0.0,Kolkata Knight Riders
3,NaN,Yes,2017,Indore,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0.0,Kings XI Punjab
4,NaN,Yes,2017,Bangalore,NaN,NaN,Royal Challengers Bangalore,bat,NaN,NaN,Royal Challengers Bangalore

In [4]:
data.loc[0]                                  # 1 st row value

id                                         1
date                                     Yes
season                                  2017
city                               Hyderabad
team1                    Sunrisers Hyderabad
team2            Royal Challengers Bangalore
toss_winner      Royal Challengers Bangalore
toss_decision                          field
result                                normal
dl_applied                                 0
winner                   Sunrisers Hyderabad
Name: 0, dtype: object

In [5]:
data.loc[4]                                    # 4 rth row value

id                                       NaN
date                                     Yes
season                                  2017
city                               Bangalore
team1                                    NaN
team2                                    NaN
toss_winner      Royal Challengers Bangalore
toss_decision                            bat
result                                   NaN
dl_applied                               NaN
winner           Royal Challengers Bangalore
Name: 4, dtype: object

In [6]:
data.loc[[2,5]]                         # list of row

,id,date,season,city,team1,team2,toss_winner,toss_decision,result,dl_applied,winner
2,3.0,Yes,2017,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0.0,Kolkata Knight Riders
5,NaN,Yes,2017,Hyderabad,NaN,NaN,Sunrisers Hyderabad,field,NaN,NaN,Sunrisers Hyderabad

In [7]:
data.loc[4, 'city']                 # perticular value

'Bangalore'

In [8]:
data.loc[0:5, 'city']

0    Hyderabad
1         Pune
2       Rajkot
3       Indore
4    Bangalore
5    Hyderabad
Name: city, dtype: object

In [9]:
data.loc[0:4,  'winner']

0            Sunrisers Hyderabad
1         Rising Pune Supergiant
2          Kolkata Knight Riders
3                Kings XI Punjab
4    Royal Challengers Bangalore
Name: winner, dtype: object

In [10]:
data.loc[data['id']< 11]

,id,date,season,city,team1,team2,toss_winner,toss_decision,result,dl_applied,winner
0,1.0,Yes,2017,Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0.0,Sunrisers Hyderabad
1,2.0,Yes,2017,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0.0,Rising Pune Supergiant
2,3.0,Yes,2017,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0.0,Kolkata Knight Riders

In [11]:
data.loc[data['id']< 11, ['team1']]

                 team1
0  Sunrisers Hyderabad
1       Mumbai Indians
2        Gujarat Lions

### iloc     --- interger location based indexing

In [12]:
data.iloc[1,3]

'Pune'

In [13]:
data.iloc[3:5,6:8]

                   toss_winner toss_decision
3              Kings XI Punjab         field
4  Royal Challengers Bangalore           bat

In [14]:
#data.loc[:,3]          show error use iloc

In [15]:
data.iloc[:,:]

,id,date,season,city,team1,team2,toss_winner,toss_decision,result,dl_applied,winner
0,1.0,Yes,2017,Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0.0,Sunrisers Hyderabad
1,2.0,Yes,2017,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0.0,Rising Pune Supergiant
2,3.0,Yes,2017,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0.0,Kolkata Knight Riders
3,NaN,Yes,2017,Indore,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0.0,Kings XI Punjab
4,NaN,Yes,2017,Bangalore,NaN,NaN,Royal Challengers Bangalore,bat,NaN,NaN,Royal Challengers Bangalore
...,...,...,...,...,...,...,...,...,...,...,...
373,374.0,No,2012,Dharamsala,Kings XI Punjab,Delhi Daredevils,Delhi Daredevils,field,normal,0.0,Delhi Daredevils
374,375.0,No,2012,Pune,Kolkata Knight Riders,Pune Warriors,Kolkata Knight Riders,bat,normal,0.0,Kolkata Knight Riders
375,376.0,No,2012,Hyderabad,Deccan Chargers,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0.0,Deccan Chargers
376,377.0,No,2012,Jaipur,Rajasthan Royals,Mumbai Indians,Rajasthan Royals,bat,normal,0.0,Mumbai Indians
377,378.0,No,2012,Pune,Kolkata Knight Riders,Delhi Daredevils,Kolkata Knight Riders,bat,normal,0.0,Kolkata Knight Riders

# groupby

### Pandas groupby function is used to split the data into groups based on some criteria

In [16]:
data = pd.read_csv('matches.csv')
data.head()

,id,date,season,city,team1,team2,toss_winner,toss_decision,result,dl_applied,winner
0,1.0,Yes,2017,Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0.0,Sunrisers Hyderabad
1,2.0,Yes,2017,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0.0,Rising Pune Supergiant
2,3.0,Yes,2017,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0.0,Kolkata Knight Riders
3,NaN,Yes,2017,Indore,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0.0,Kings XI Punjab
4,NaN,Yes,2017,Bangalore,NaN,NaN,Royal Challengers Bangalore,bat,NaN,NaN,Royal Challengers Bangalore

In [17]:
g1 = data.groupby(by = 'city')

In [18]:
g1

In [19]:
g1.groups

{'Ahmedabad': Int64Index([179, 186, 194, 197], dtype='int64'),
 'Bangalore': Int64Index([  4,  11,  16,  29,  41,  44,  56,  57,  59,  69,  73,  83,  89,
             103, 110, 180, 183, 191, 196, 213, 216, 225, 241, 267, 279, 282,
             290, 301, 311, 316, 325, 328, 349, 355, 366],
            dtype='int64'),
 'Bloemfontein': Int64Index([160, 164], dtype='int64'),
 'Cape Town': Int64Index([117, 118, 119, 120, 123, 125, 129], dtype='int64'),
 'Centurion': Int64Index([132, 135, 136, 146, 147, 148, 155, 156, 165, 169, 170, 171], dtype='int64'),
 'Chandigarh': Int64Index([ 31,  34,  45,  47,  60,  68,  72,  80,  93,  96, 107, 176, 192,
             195, 204, 214, 242, 255, 283, 286, 320, 329, 332, 339, 353, 365],
            dtype='int64'),
 'Chennai': Int64Index([ 66,  70,  78,  84,  90, 106, 109, 178, 189, 201, 205, 210, 221,
             223, 234, 247, 261, 271, 275, 288, 296, 305, 306, 307, 319, 331,
             333, 342, 346, 351, 363],
            dtype='int64'),
 'Cuttack': Int64Index([185, 188, 336, 347], dtype='int64'),
 'Delhi': Int64Index([ 14,  17,  38,  40,  43,  50,  54,  61,  75,  86,  97,  99, 108,
             182, 184, 199, 202, 208, 217, 228, 237, 252, 258, 262, 265, 273,
             300, 317, 322, 334, 341, 344, 356, 368, 371],
            dtype='int64'),
 'Dharamsala': Int64Index([224, 227, 292, 295, 299, 370, 373], dtype='int64'),
 'Durban': Int64Index([122, 124, 126, 127, 130, 133, 134, 138, 144, 145, 157, 158, 159,
             167, 168],
            dtype='int64'),
 'East London': Int64Index([137, 143, 149], dtype='int64'),
 'Hyderabad': Int64Index([  0,   5,  18,  20,  35,  42,  46,  58,  65,  67,  76,  79,  91,
             101, 113, 235, 244, 248, 259, 274, 278, 285, 330, 358, 372, 375],
            dtype='int64'),
 'Indore': Int64Index([3, 7, 21, 289, 293], dtype='int64'),
 'Jaipur': Int64Index([ 64,  77,  82,  88,  92, 100, 112, 211, 218, 222, 240, 245, 260,
             266, 270, 284, 287, 310, 313, 327, 337, 348, 360, 364, 376],
            dtype='int64'),
 'Johannesburg': Int64Index([140, 142, 153, 162, 163, 166, 172, 173], dtype='int64'),
 'Kanpur': Int64Index([48, 51], dtype='int64'),
 'Kimberley': Int64Index([150, 151, 154], dtype='int64'),
 'Kochi': Int64Index([236, 251, 264, 268, 277], dtype='int64'),
 'Kolkata': Int64Index([ 10,  13,  22,  26,  30,  39,  52,  63,  74,  87,  94, 102, 104,
             111, 177, 181, 203, 207, 212, 226, 229, 239, 250, 254, 257, 269,
             280, 302, 308, 321, 324, 343, 352, 362, 367],
            dtype='int64'),
 'Mumbai': Int64Index([  6,   9,  15,  23,  27,  36,  49,  55,  62,  71,  81,  85,  95,
              98, 105, 114, 115, 116, 174, 175, 187, 190, 193, 198, 200, 206,
             220, 230, 231, 232, 233, 238, 243, 246, 249, 253, 256, 263, 272,
             276, 281, 291, 294, 297, 298, 303, 304, 309, 318, 326, 335, 345,
             354, 359, 369],
            dtype='int64'),
 'Nagpur': Int64Index([209, 215, 219], dtype='int64'),
 'Port Elizabeth': Int64Index([121, 128, 131, 139, 141, 152, 161], dtype='int64'),
 'Pune': Int64Index([1, 8, 24, 28, 32, 37, 53, 314, 323, 338, 340, 350, 357, 361, 374,
             377],
            dtype='int64'),
 'Rajkot': Int64Index([2, 12, 19, 25, 33], dtype='int64'),
 'Visakhapatnam': Int64Index([312, 315], dtype='int64')}

In [20]:
g1 = data.groupby(['city','team1'])

In [21]:
g1

In [22]:
g1.groups

{('Hyderabad',
  'Sunrisers Hyderabad'): Int64Index([0, 18, 20, 35], dtype='int64'),
 ('Pune', 'Mumbai Indians'): Int64Index([1, 350], dtype='int64'),
 ('Rajkot', 'Gujarat Lions'): Int64Index([2, 33], dtype='int64'),
 ('Indore', 'Rising Pune Supergiant'): Int64Index([3], dtype='int64'),
 ('Bangalore', nan): Int64Index([4], dtype='int64'),
 ('Hyderabad', nan): Int64Index([5], dtype='int64'),
 ('Mumbai', nan): Int64Index([6], dtype='int64'),
 ('Indore', nan): Int64Index([7], dtype='int64'),
 ('Pune', nan): Int64Index([8], dtype='int64'),
 ('Mumbai', 'Sunrisers Hyderabad'): Int64Index([9], dtype='int64'),
 ('Kolkata',
  'Kings XI Punjab'): Int64Index([10, 111, 269, 324], dtype='int64'),
 ('Bangalore',
  'Royal Challengers Bangalore'): Int64Index([11, 29, 44, 69, 83, 89, 103, 110, 191, 213, 241, 267, 279, 311,
             349, 366],
            dtype='int64'),
 ('Rajkot', 'Rising Pune Supergiant'): Int64Index([12], dtype='int64'),
 ('Kolkata',
  'Kolkata Knight Riders'): Int64Index([ 13,  22,  26,  39,  74,  87,  94, 102, 104, 203, 207, 212, 239,
             257, 302, 308, 343, 352, 367],
            dtype='int64'),
 ('Delhi',
  'Delhi Daredevils'): Int64Index([ 14,  17,  50,  75,  86,  97,  99, 184, 199, 202, 208, 217, 237,
             258, 262, 273, 300, 341, 344, 356],
            dtype='int64'),
 ('Mumbai', 'Gujarat Lions'): Int64Index([15], dtype='int64'),
 ('Bangalore', 'Rising Pune Supergiant'): Int64Index([16], dtype='int64'),
 ('Rajkot', 'Royal Challengers Bangalore'): Int64Index([19], dtype='int64'),
 ('Indore', 'Kings XI Punjab'): Int64Index([21], dtype='int64'),
 ('Mumbai',
  'Mumbai Indians'): Int64Index([ 23,  62,  71,  81, 175, 187, 198, 206, 220, 230, 246, 256, 272,
             276, 281, 298, 318, 326, 335, 359],
            dtype='int64'),
 ('Pune', 'Sunrisers Hyderabad'): Int64Index([24], dtype='int64'),
 ('Rajkot', 'Kings XI Punjab'): Int64Index([25], dtype='int64'),
 ('Mumbai', 'Rising Pune Supergiant'): Int64Index([27, 55], dtype='int64'),
 ('Pune', 'Rising Pune Supergiant'): Int64Index([28, 32], dtype='int64'),
 ('Kolkata', 'Delhi Daredevils'): Int64Index([30], dtype='int64'),
 ('Chandigarh', 'Sunrisers Hyderabad'): Int64Index([31], dtype='int64'),
 ('Chandigarh', 'Delhi Daredevils'): Int64Index([34, 72], dtype='int64'),
 ('Mumbai',
  'Royal Challengers Bangalore'): Int64Index([36, 303], dtype='int64'),
 ('Pune', 'Gujarat Lions'): Int64Index([37], dtype='int64'),
 ('Delhi', 'Sunrisers Hyderabad'): Int64Index([38], dtype='int64'),
 ('Delhi', 'Gujarat Lions'): Int64Index([40], dtype='int64'),
 ('Bangalore', 'Kings XI Punjab'): Int64Index([41, 180], dtype='int64'),
 ('Hyderabad', 'Rising Pune Supergiant'): Int64Index([42], dtype='int64'),
 ('Delhi', 'Mumbai Indians'): Int64Index([43, 108, 182], dtype='int64'),
 ('Chandigarh',
  'Kings XI Punjab'): Int64Index([45, 47, 68, 80, 96, 176, 204, 255, 283, 286, 329, 332, 339], dtype='int64'),
 ('Hyderabad',
  'Mumbai Indians'): Int64Index([46, 58, 101, 259], dtype='int64'),
 ('Kanpur', 'Gujarat Lions'): Int64Index([48, 51], dtype='int64'),
 ('Mumbai',
  'Kings XI Punjab'): Int64Index([49, 105, 115, 200, 238], dtype='int64'),
 ('Kolkata', 'Mumbai Indians'): Int64Index([52, 229, 362], dtype='int64'),
 ('Pune', 'Kings XI Punjab'): Int64Index([53], dtype='int64'),
 ('Delhi',
  'Royal Challengers Bangalore'): Int64Index([54, 371], dtype='int64'),
 ('Bangalore', 'Sunrisers Hyderabad'): Int64Index([56], dtype='int64'),
 ('Bangalore',
  'Kolkata Knight Riders'): Int64Index([57, 59, 216, 290, 316], dtype='int64'),
 ('Chandigarh', 'Chennai Super Kings'): Int64Index([60, 242], dtype='int64'),
 ('Delhi', 'Rajasthan Royals'): Int64Index([61], dtype='int64'),
 ('Kolkata', 'Deccan Chargers'): Int64Index([63], dtype='int64'),
 ('Jaipur', 'Kings XI Punjab'): Int64Index([64, 211], dtype='int64'),
 ('Hyderabad',
  'Deccan Chargers'): Int64Index([65, 67, 76, 79, 113, 235, 244, 248, 278, 285, 330, 375], dtype='int64'),
 ('Chennai',
  'Chennai Super Kings'): Int64Index([ 66,  78,  84,  90, 205, 210, 223, 234, 247, 261, 271, 288, 296,
             306, 307, 331, 346, 351],
            dtype='int64'),
 ('Chennai', 'Kolkata Knight Riders'): Int64Index([70, 221], dtype='int64'),
 ('Bangalore', 'Chennai Super Kings'): Int64Index([73, 301], dtype='int64'),
 ('Jaipur',
  'Rajasthan Royals'): Int64Index([77, 100, 222, 245, 287, 310, 313, 348, 360, 364, 376], dtype='int64'),
 ('Jaipur', 'Chennai Super Kings'): Int64Index([82, 284], dtype='int64'),
 ('Mumbai', 'Rajasthan Royals'): Int64Index([85, 114], dtype='int64'),
 ('Jaipur', 'Deccan Chargers'): Int64Index([88, 327], dtype='int64'),
 ('Hyderabad', 'Kolkata Knight Riders'): Int64Index([91, 274], dtype='int64'),
 ('Jaipur', 'Delhi Daredevils'): Int64Index([92, 240], dtype='int64'),
 ('Chandigarh',
  'Royal Challengers Bangalore'): Int64Index([93], dtype='int64'),
 ('Mumbai',
  'Chennai Super Kings'): Int64Index([95, 116, 193, 231, 233, 354], dtype='int64'),
 ('Mumbai',
  'Kolkata Knight Riders'): Int64Index([98, 174, 190, 304, 369], dtype='int64'),
 ('Chennai',
  'Royal Challengers Bangalore'): Int64Index([106, 201, 305, 319], dtype='int64'),
 ('Chandigarh', 'Deccan Chargers'): Int64Index([107, 365], dtype='int64'),
 ('Chennai', 'Rajasthan Royals'): Int64Index([109, 275, 333], dtype='int64'),
 ('Jaipur', 'Mumbai Indians'): Int64Index([112, 218, 266], dtype='int64'),
 ('Cape Town', 'Mumbai Indians'): Int64Index([117], dtype='int64'),
 ('Cape Town',
  'Royal Challengers Bangalore'): Int64Index([118], dtype='int64'),
 ('Cape Town', 'Kings XI Punjab'): Int64Index([119, 129], dtype='int64'),
 ('Cape Town', 'Kolkata Knight Riders'): Int64Index([120], dtype='int64'),
 ('Port Elizabeth', 'Chennai Super Kings'): Int64Index([121], dtype='int64'),
 ('Durban', 'Kings XI Punjab'): Int64Index([122, 134], dtype='int64'),
 ('Cape Town', 'Deccan Chargers'): Int64Index([123], dtype='int64'),
 ('Durban', 'Delhi Daredevils'): Int64Index([124, 157], dtype='int64'),
 ('Cape Town', 'Rajasthan Royals'): Int64Index([125], dtype='int64'),
 ('Durban',
  'Royal Challengers Bangalore'): Int64Index([126, 138], dtype='int64'),
 ('Durban', 'Deccan Chargers'): Int64Index([127], dtype='int64'),
 ('Port Elizabeth',
  'Royal Challengers Bangalore'): Int64Index([128], dtype='int64'),
 ('Durban', 'Chennai Super Kings'): Int64Index([130, 158, 168], dtype='int64'),
 ('Port Elizabeth',
  'Mumbai Indians'): Int64Index([131, 152, 161], dtype='int64'),
 ('Centurion', 'Delhi Daredevils'): Int64Index([132, 171], dtype='int64'),
 ('Durban', 'Kolkata Knight Riders'): Int64Index([133, 145], dtype='int64'),
 ('Centurion', 'Deccan Chargers'): Int64Index([135, 146], dtype='int64'),
 ('Centurion',
  'Chennai Super Kings'): Int64Index([136, 148, 165], dtype='int64'),
 ('East London', 'Mumbai Indians'): Int64Index([137, 149], dtype='int64'),
 ('Port Elizabeth', 'Deccan Chargers'): Int64Index([139], dtype='int64'),
 ('Johannesburg',
  'Chennai Super Kings'): Int64Index([140, 172], dtype='int64'),
 ('Port Elizabeth', 'Kolkata Knight Riders'): Int64Index([141], dtype='int64'),
 ('Johannesburg', 'Mumbai Indians'): Int64Index([142], dtype='int64'),
 ('East London', 'Chennai Super Kings'): Int64Index([143], dtype='int64'),
 ('Durban', 'Rajasthan Royals'): Int64Index([144, 159, 167], dtype='int64'),
 ('Centurion',
  'Royal Challengers Bangalore'): Int64Index([147, 170], dtype='int64'),
 ('Kimberley', 'Deccan Chargers'): Int64Index([150, 154], dtype='int64'),
 ('Kimberley', 'Rajasthan Royals'): Int64Index([151], dtype='int64'),
 ('Johannesburg',
  'Kolkata Knight Riders'): Int64Index([153, 162], dtype='int64'),
 ('Centurion', 'Kolkata Knight Riders'): Int64Index([155], dtype='int64'),
 ('Centurion', 'Kings XI Punjab'): Int64Index([156], dtype='int64'),
 ('Bloemfontein', 'Delhi Daredevils'): Int64Index([160, 164], dtype='int64'),
 ('Johannesburg', 'Kings XI Punjab'): Int64Index([163], dtype='int64'),
 ('Johannesburg', 'Delhi Daredevils'): Int64Index([166], dtype='int64'),
 ('Centurion', 'Mumbai Indians'): Int64Index([169], dtype='int64'),
 ('Johannesburg', 'Deccan Chargers'): Int64Index([173], dtype='int64'),
 ('Kolkata', 'Royal Challengers Bangalore'): Int64Index([177], dtype='int64'),
 ('Chennai', 'Deccan Chargers'): Int64Index([178], dtype='int64'),
 ('Ahmedabad', 'Rajasthan Royals'): Int64Index([179, 186, 197], dtype='int64'),
 ('Kolkata', 'Chennai Super Kings'): Int64Index([181, 280], dtype='int64'),
 ('Bangalore', 'Rajasthan Royals'): Int64Index([183, 325], dtype='int64'),
 ('Cuttack',
  'Deccan Chargers'): Int64Index([185, 188, 336, 347], dtype='int64'),
 ('Chennai', 'Kings XI Punjab'): Int64Index([189, 342], dtype='int64'),
 ('Chandigarh', 'Rajasthan Royals'): Int64Index([192, 353], dtype='int64'),
 ('Ahmedabad', 'Deccan Chargers'): Int64Index([194], dtype='int64'),
 ('Chandigarh', 'Kolkata Knight Riders'): Int64Index([195], dtype='int64'),
 ('Bangalore', 'Delhi Daredevils'): Int64Index([196], dtype='int64'),
 ('Nagpur', 'Rajasthan Royals'): Int64Index([209], dtype='int64'),
 ('Chandigarh', 'Mumbai Indians'): Int64Index([214], dtype='int64'),
 ('Nagpur', 'Chennai Super Kings'): Int64Index([215], dtype='int64'),
 ('Nagpur', 'Deccan Chargers'): Int64Index([219], dtype='int64'),
 ('Dharamsala',
  'Kings XI Punjab'): Int64Index([224, 227, 292, 295, 373], dtype='int64'),
 ('Bangalore', 'Mumbai Indians'): Int64Index([225], dtype='int64'),
 ('Kolkata', 'Rajasthan Royals'): Int64Index([226, 250, 321], dtype='int64'),
 ('Delhi', 'Deccan Chargers'): Int64Index([228, 252, 322], dtype='int64'),
 ('Mumbai', 'Deccan Chargers'): Int64Index([232, 291, 345], dtype='int64'),
 ('Kochi', 'Kochi Tuskers Kerala'): Int64Index([236, 277], dtype='int64'),
 ('Mumbai', 'Kochi Tuskers Kerala'): Int64Index([243], dtype='int64'),
 ('Mumbai',
  'Pune Warriors'): Int64Index([249, 253, 263, 294, 297, 309], dtype='int64'),
 ('Kochi', 'Chennai Super Kings'): Int64Index([251], dtype='int64'),
 ('Kolkata', 'Kochi Tuskers Kerala'): Int64Index([254], dtype='int64'),
 ('Jaipur', 'Kochi Tuskers Kerala'): Int64Index([260], dtype='int64'),
 ('Kochi', 'Deccan Chargers'): Int64Index([264], dtype='int64'),
 ('Delhi', 'Kolkata Knight Riders'): Int64Index([265], dtype='int64'),
 ('Kochi', 'Delhi Daredevils'): Int64Index([268], dtype='int64'),
 ('Jaipur', 'Pune Warriors'): Int64Index([270], dtype='int64'),
 ('Bangalore', 'Kochi Tuskers Kerala'): Int64Index([282], dtype='int64'),
 ('Indore', 'Kochi Tuskers Kerala'): Int64Index([289], dtype='int64'),
 ('Indore', 'Rajasthan Royals'): Int64Index([293], dtype='int64'),
 ('Dharamsala', 'Deccan Chargers'): Int64Index([299], dtype='int64'),
 ('Visakhapatnam', 'Chennai Super Kings'): Int64Index([312], dtype='int64'),
 ('Pune', 'Pune Warriors'): Int64Index([314, 338, 357], dtype='int64'),
 ('Visakhapatnam', 'Deccan Chargers'): Int64Index([315], dtype='int64'),
 ('Delhi', 'Chennai Super Kings'): Int64Index([317], dtype='int64'),
 ('Chandigarh', 'Pune Warriors'): Int64Index([320], dtype='int64'),
 ('Pune', 'Chennai Super Kings'): Int64Index([323], dtype='int64'),
 ('Bangalore', 'Pune Warriors'): Int64Index([328], dtype='int64'),
 ('Delhi', 'Pune Warriors'): Int64Index([334], dtype='int64'),
 ('Jaipur', 'Royal Challengers Bangalore'): Int64Index([337], dtype='int64'),
 ('Pune', 'Deccan Chargers'): Int64Index([340], dtype='int64'),
 ('Bangalore', 'Deccan Chargers'): Int64Index([355], dtype='int64'),
 ('Hyderabad', 'Kings XI Punjab'): Int64Index([358], dtype='int64'),
 ('Pune', 'Royal Challengers Bangalore'): Int64Index([361], dtype='int64'),
 ('Chennai', 'Delhi Daredevils'): Int64Index([363], dtype='int64'),
 ('Delhi', 'Kings XI Punjab'): Int64Index([368], dtype='int64'),
 ('Dharamsala', 'Chennai Super Kings'): Int64Index([370], dtype='int64'),
 ('Hyderabad', 'Rajasthan Royals'): Int64Index([372], dtype='int64'),
 ('Pune', 'Kolkata Knight Riders'): Int64Index([374, 377], dtype='int64')}

In [23]:
list(g1)

[(('Ahmedabad', 'Deccan Chargers'),
          id date  season       city            team1             team2  \
  194  195.0  Yes    2010  Ahmedabad  Deccan Chargers  Rajasthan Royals

           toss_winner toss_decision  result  dl_applied            winner
  194  Deccan Chargers           bat  normal         0.0  Rajasthan Royals  ),
 (('Ahmedabad', 'Rajasthan Royals'),
          id date  season       city             team1                  team2  \
  179  180.0  Yes    2010  Ahmedabad  Rajasthan Royals       Delhi Daredevils
  186  187.0  Yes    2010  Ahmedabad  Rajasthan Royals  Kolkata Knight Riders
  197  198.0  Yes    2010  Ahmedabad  Rajasthan Royals    Chennai Super Kings

            toss_winner toss_decision  result  dl_applied            winner
  179  Delhi Daredevils         field  normal         0.0  Delhi Daredevils
  186  Rajasthan Royals           bat  normal         0.0  Rajasthan Royals
  197  Rajasthan Royals           bat  normal         0.0  Rajasthan Royals  ),
 (('Bangalore', 'Chennai Super Kings'),
          id date  season       city                team1  \
  73    74.0  Yes    2008  Bangalore  Chennai Super Kings
  301  302.0  Yes    2011  Bangalore  Chennai Super Kings

                             team2                  toss_winner toss_decision  \
  73   Royal Challengers Bangalore          Chennai Super Kings           bat
  301  Royal Challengers Bangalore  Royal Challengers Bangalore         field

       result  dl_applied                       winner
  73   normal         0.0          Chennai Super Kings
  301  normal         0.0  Royal Challengers Bangalore  ),
 (('Bangalore', 'Deccan Chargers'),
          id date  season       city            team1  \
  355  356.0   No    2012  Bangalore  Deccan Chargers

                             team2                  toss_winner toss_decision  \
  355  Royal Challengers Bangalore  Royal Challengers Bangalore         field

       result  dl_applied                       winner
  355  normal         0.0  Royal Challengers Bangalore  ),
 (('Bangalore', 'Delhi Daredevils'),
          id date  season       city             team1  \
  196  197.0  Yes    2010  Bangalore  Delhi Daredevils

                             team2                  toss_winner toss_decision  \
  196  Royal Challengers Bangalore  Royal Challengers Bangalore         field

       result  dl_applied            winner
  196  normal         0.0  Delhi Daredevils  ),
 (('Bangalore', 'Kings XI Punjab'),
          id date  season       city            team1  \
  41    42.0  Yes    2017  Bangalore  Kings XI Punjab
  180  181.0  Yes    2010  Bangalore  Kings XI Punjab

                             team2                  toss_winner toss_decision  \
  41   Royal Challengers Bangalore  Royal Challengers Bangalore         field
  180  Royal Challengers Bangalore              Kings XI Punjab           bat

       result  dl_applied                       winner
  41   normal         0.0              Kings XI Punjab
  180  normal         0.0  Royal Challengers Bangalore  ),
 (('Bangalore', 'Kochi Tuskers Kerala'),
          id date  season       city                 team1  \
  282  283.0  Yes    2011  Bangalore  Kochi Tuskers Kerala

                             team2           toss_winner toss_decision  result  \
  282  Royal Challengers Bangalore  Kochi Tuskers Kerala           bat  normal

       dl_applied                       winner
  282         0.0  Royal Challengers Bangalore  ),
 (('Bangalore', 'Kolkata Knight Riders'),
          id date  season       city                  team1  \
  57    58.0  Yes    2017  Bangalore  Kolkata Knight Riders
  59    60.0  Yes    2008  Bangalore  Kolkata Knight Riders
  216  217.0  Yes    2010  Bangalore  Kolkata Knight Riders
  290  291.0  Yes    2011  Bangalore  Kolkata Knight Riders
  316  317.0  Yes    2012  Bangalore  Kolkata Knight Riders

                             team2                  toss_winner toss_decision  \
  57                Mumbai Indians               Mumbai Indians         field
  59   Royal Challengers Bangalore  Royal Challengers Bangalore         field
  216  Royal Challengers Bangalore  Royal Challengers Bangalore         field
  290  Royal Challengers Bangalore  Royal Challengers Bangalore         field
  316  Royal Challengers Bangalore  Royal Challengers Bangalore         field

       result  dl_applied                       winner
  57   normal         0.0               Mumbai Indians
  59   normal         0.0        Kolkata Knight Riders
  216  normal         0.0  Royal Challengers Bangalore
  290  normal         1.0  Royal Challengers Bangalore
  316  normal         0.0        Kolkata Knight Riders  ),
 (('Bangalore', 'Mumbai Indians'),
          id date  season       city           team1  \
  225  226.0  Yes    2010  Bangalore  Mumbai Indians

                             team2                  toss_winner toss_decision  \
  225  Royal Challengers Bangalore  Royal Challengers Bangalore         field

       result  dl_applied          winner
  225  normal         0.0  Mumbai Indians  ),
 (('Bangalore', 'Pune Warriors'),
          id date  season       city          team1  \
  328  329.0  Yes    2012  Bangalore  Pune Warriors

                             team2    toss_winner toss_decision  result  \
  328  Royal Challengers Bangalore  Pune Warriors           bat  normal

       dl_applied                       winner
  328         0.0  Royal Challengers Bangalore  ),
 (('Bangalore', 'Rajasthan Royals'),
          id date  season       city             team1  \
  183  184.0  Yes    2010  Bangalore  Rajasthan Royals
  325  326.0  Yes    2012  Bangalore  Rajasthan Royals

                             team2                  toss_winner toss_decision  \
  183  Royal Challengers Bangalore  Royal Challengers Bangalore         field
  325  Royal Challengers Bangalore             Rajasthan Royals           bat

       result  dl_applied                       winner
  183  normal         0.0  Royal Challengers Bangalore
  325  normal         0.0             Rajasthan Royals  ),
 (('Bangalore', 'Rising Pune Supergiant'),
        id date  season       city                   team1  \
  16  17.0  Yes    2017  Bangalore  Rising Pune Supergiant

                            team2                  toss_winner toss_decision  \
  16  Royal Challengers Bangalore  Royal Challengers Bangalore         field

      result  dl_applied                  winner
  16  normal         0.0  Rising Pune Supergiant  ),
 (('Bangalore', 'Royal Challengers Bangalore'),
          id date  season       city                        team1  \
  11    12.0  Yes    2017  Bangalore  Royal Challengers Bangalore
  29    30.0  Yes    2017  Bangalore  Royal Challengers Bangalore
  44    45.0  Yes    2017  Bangalore  Royal Challengers Bangalore
  69    70.0  Yes    2008  Bangalore  Royal Challengers Bangalore
  83    84.0  Yes    2008  Bangalore  Royal Challengers Bangalore
  89    90.0  Yes    2008  Bangalore  Royal Challengers Bangalore
  103  104.0  Yes    2008  Bangalore  Royal Challengers Bangalore
  110  111.0  Yes    2008  Bangalore  Royal Challengers Bangalore
  191  192.0  Yes    2010  Bangalore  Royal Challengers Bangalore
  213  214.0  Yes    2010  Bangalore  Royal Challengers Bangalore
  241  242.0  Yes    2011  Bangalore  Royal Challengers Bangalore
  267  268.0  Yes    2011  Bangalore  Royal Challengers Bangalore
  279  280.0  Yes    2011  Bangalore  Royal Challengers Bangalore
  311  312.0  Yes    2012  Bangalore  Royal Challengers Bangalore
  349  350.0  Yes    2012  Bangalore  Royal Challengers Bangalore
  366  367.0   No    2012  Bangalore  Royal Challengers Bangalore

                       team2            toss_winner toss_decision  result  \
  11          Mumbai Indians         Mumbai Indians         field  normal
  29           Gujarat Lions          Gujarat Lions         field  normal
  44   Kolkata Knight Riders  Kolkata Knight Riders         field  normal
  69        Rajasthan Royals       Rajasthan Royals         field  normal
  83         Kings XI Punjab        Kings XI Punjab         field  normal
  89          Mumbai Indians         Mumbai Indians         field  normal
  103       Delhi Daredevils       Delhi Daredevils         field  normal
  110        Deccan Chargers        Deccan Chargers         field  normal
  191    Chennai Super Kings    Chennai Super Kings         field  normal
  213        Deccan Chargers        Deccan Chargers         field  normal
  241         Mumbai Indians         Mumbai Indians         field  normal
  267          Pune Warriors          Pune Warriors         field  normal
  279        Kings XI Punjab        Kings XI Punjab         field  normal
  311       Delhi Daredevils       Delhi Daredevils         field  normal
  349        Kings XI Punjab        Kings XI Punjab         field  normal
  366         Mumbai Indians         Mumbai Indians         field  normal

       dl_applied                       winner
  11          NaN               Mumbai Indians
  29          0.0                Gujarat Lions
  44          0.0        Kolkata Knight Riders
  69          0.0             Rajasthan Royals
  83          0.0              Kings XI Punjab
  89          0.0               Mumbai Indians
  103         0.0             Delhi Daredevils
  110         0.0  Royal Challengers Bangalore
  191         0.0  Royal Challengers Bangalore
  213         0.0              Deccan Chargers
  241         0.0               Mumbai Indians
  267         0.0  Royal Challengers Bangalore
  279         0.0  Royal Challengers Bangalore
  311         0.0  Royal Challengers Bangalore
  349         0.0              Kings XI Punjab
  366         0.0               Mumbai Indians  ),
 (('Bangalore', 'Sunrisers Hyderabad'),
        id date  season       city                team1                  team2  \
  56  57.0  Yes    2017  Bangalore  Sunrisers Hyderabad  Kolkata Knight Riders

                toss_winner toss_decision  result  dl_applied  \
  56  Kolkata Knight Riders         field  normal         1.0

                     winner
  56  Kolkata Knight Riders  ),
 (('Bloemfontein', 'Delhi Daredevils'),
          id date  season          city             team1             team2  \
  160  161.0  Yes    2009  Bloemfontein  Delhi Daredevils   Kings XI Punjab
  164  165.0  Yes    2009  Bloemfontein  Delhi Daredevils  Rajasthan Royals

            toss_winner toss_decision  result  dl_applied            winner
  160   Kings XI Punjab         field  normal         0.0   Kings XI Punjab
  164  Delhi Daredevils           bat  normal         0.0  Delhi Daredevils  ),
 (('Cape Town', 'Deccan Chargers'),
          id date  season       city            team1  \
  123  124.0  Yes    2009  Cape Town  Deccan Chargers

                             team2      toss_winner toss_decision  result  \
  123  Royal Challengers Bangalore  Deccan Chargers           bat  normal

       dl_applied           winner
  123         0.0  Deccan Chargers  ),
 (('Cape Town', 'Kings XI Punjab'),
          id date  season       city            team1             team2  \
  119  120.0  Yes    2009  Cape Town  Kings XI Punjab  Delhi Daredevils
  129  130.0  Yes    2009  Cape Town  Kings XI Punjab  Rajasthan Royals

            toss_winner toss_decision  result  dl_applied            winner
  119  Delhi Daredevils         field  normal         1.0  Delhi Daredevils
  129   Kings XI Punjab           bat  normal         0.0   Kings XI Punjab  ),
 (('Cape Town', 'Kolkata Knight Riders'),
          id date  season       city                  team1            team2  \
  120  121.0  Yes    2009  Cape Town  Kolkata Knight Riders  Deccan Chargers

                 toss_winner toss_decision  result  dl_applied           winner
  120  Kolkata Knight Riders           bat  normal         0.0  Deccan Chargers  ),
 (('Cape Town', 'Mumbai Indians'),
          id date  season       city           team1                team2  \
  117  118.0  Yes    2009  Cape Town  Mumbai Indians  Chennai Super Kings

               toss_winner toss_decision  result  dl_applied          winner
  117  Chennai Super Kings         field  normal         0.0  Mumbai Indians  ),
 (('Cape Town', 'Rajasthan Royals'),
          id date  season       city             team1                  team2  \
  125  126.0  Yes    2009  Cape Town  Rajasthan Royals  Kolkata Knight Riders

                 toss_winner toss_decision result  dl_applied            winner
  125  Kolkata Knight Riders         field    tie         0.0  Rajasthan Royals  ),
 (('Cape Town', 'Royal Challengers Bangalore'),
          id date  season       city                        team1  \
  118  119.0  Yes    2009  Cape Town  Royal Challengers Bangalore

                  team2                  toss_winner toss_decision  result  \
  118  Rajasthan Royals  Royal Challengers Bangalore           bat  normal

       dl_applied                       winner
  118         0.0  Royal Challengers Bangalore  ),
 (('Centurion', 'Chennai Super Kings'),
          id date  season       city                team1  \
  136  137.0  Yes    2009  Centurion  Chennai Super Kings
  148  149.0  Yes    2009  Centurion  Chennai Super Kings
  165  166.0  Yes    2009  Centurion  Chennai Super Kings

                       team2          toss_winner toss_decision  result  \
  136       Rajasthan Royals     Rajasthan Royals         field  normal
  148        Kings XI Punjab  Chennai Super Kings           bat  normal
  165  Kolkata Knight Riders  Chennai Super Kings           bat  normal

       dl_applied                 winner
  136         0.0    Chennai Super Kings
  148         1.0    Chennai Super Kings
  165         0.0  Kolkata Knight Riders  ),
 (('Centurion', 'Deccan Chargers'),
          id date  season       city            team1             team2  \
  135  136.0  Yes    2009  Centurion  Deccan Chargers  Delhi Daredevils
  146  147.0  Yes    2009  Centurion  Deccan Chargers    Mumbai Indians

            toss_winner toss_decision  result  dl_applied            winner
  135  Delhi Daredevils         field  normal         0.0  Delhi Daredevils
  146   Deccan Chargers           bat  normal         0.0   Deccan Chargers  ),
 (('Centurion', 'Delhi Daredevils'),
          id date  season       city             team1             team2  \
  132  133.0  Yes    2009  Centurion  Delhi Daredevils  Rajasthan Royals
  171  172.0  Yes    2009  Centurion  Delhi Daredevils   Deccan Chargers

            toss_winner toss_decision  result  dl_applied            winner
  132  Delhi Daredevils           bat  normal         0.0  Rajasthan Royals
  171   Deccan Chargers         field  normal         0.0   Deccan Chargers  ),
 (('Centurion', 'Kings XI Punjab'),
          id date  season       city            team1           team2  \
  156  157.0  Yes    2009  Centurion  Kings XI Punjab  Mumbai Indians

           toss_winner toss_decision  result  dl_applied          winner
  156  Kings XI Punjab           bat  normal         0.0  Mumbai Indians  ),
 (('Centurion', 'Kolkata Knight Riders'),
          id date  season       city                  team1  \
  155  156.0  Yes    2009  Centurion  Kolkata Knight Riders

                             team2                  toss_winner toss_decision  \
  155  Royal Challengers Bangalore  Royal Challengers Bangalore         field

       result  dl_applied                       winner
  155  normal         0.0  Royal Challengers Bangalore  ),
 (('Centurion', 'Mumbai Indians'),
          id date  season       city           team1             team2  \
  169  170.0  Yes    2009  Centurion  Mumbai Indians  Delhi Daredevils

            toss_winner toss_decision  result  dl_applied            winner
  169  Delhi Daredevils         field  normal         0.0  Delhi Daredevils  ),
 (('Centurion', 'Royal Challengers Bangalore'),
          id date  season       city                        team1  \
  147  148.0  Yes    2009  Centurion  Royal Challengers Bangalore
  170  171.0  Yes    2009  Centurion  Royal Challengers Bangalore

                  team2                  toss_winner toss_decision  result  \
  147  Rajasthan Royals             Rajasthan Royals         field  normal
  170   Deccan Chargers  Royal Challengers Bangalore           bat  normal

       dl_applied                       winner
  147         0.0             Rajasthan Royals
  170         0.0  Royal Challengers Bangalore  ),
 (('Chandigarh', 'Chennai Super Kings'),
          id date  season        city                team1            team2  \
  60    61.0  Yes    2008  Chandigarh  Chennai Super Kings  Kings XI Punjab
  242  243.0  Yes    2011  Chandigarh  Chennai Super Kings  Kings XI Punjab

               toss_winner toss_decision  result  dl_applied  \
  60   Chennai Super Kings           bat  normal         0.0
  242      Kings XI Punjab         field  normal         0.0

                    winner
  60   Chennai Super Kings
  242      Kings XI Punjab  ),
 (('Chandigarh', 'Deccan Chargers'),
          id date  season        city            team1            team2  \
  107  108.0  Yes    2008  Chandigarh  Deccan Chargers  Kings XI Punjab
  365  366.0   No    2012  Chandigarh  Deccan Chargers  Kings XI Punjab

           toss_winner toss_decision  result  dl_applied           winner
  107  Kings XI Punjab         field  normal         0.0  Kings XI Punjab
  365  Deccan Chargers           bat  normal         0.0  Kings XI Punjab  ),
 (('Chandigarh', 'Delhi Daredevils'),
        id date  season        city             team1            team2  \
  34  35.0  Yes    2017  Chandigarh  Delhi Daredevils  Kings XI Punjab
  72  73.0  Yes    2008  Chandigarh  Delhi Daredevils  Kings XI Punjab

           toss_winner toss_decision  result  dl_applied           winner
  34   Kings XI Punjab         field  normal         0.0  Kings XI Punjab
  72  Delhi Daredevils           bat  normal         0.0  Kings XI Punjab  ),
 (('Chandigarh', 'Kings XI Punjab'),
          id date  season        city            team1  \
  45    46.0  Yes    2017  Chandigarh  Kings XI Punjab
  47    48.0  Yes    2017  Chandigarh  Kings XI Punjab
  68    69.0  Yes    2008  Chandigarh  Kings XI Punjab
  80    81.0  Yes    2008  Chandigarh  Kings XI Punjab
  96    97.0  Yes    2008  Chandigarh  Kings XI Punjab
  176  177.0  Yes    2010  Chandigarh  Kings XI Punjab
  204  205.0  Yes    2010  Chandigarh  Kings XI Punjab
  255  256.0  Yes    2011  Chandigarh  Kings XI Punjab
  283  284.0  Yes    2011  Chandigarh  Kings XI Punjab
  286  287.0  Yes    2011  Chandigarh  Kings XI Punjab
  329  330.0  Yes    2012  Chandigarh  Kings XI Punjab
  332  333.0  Yes    2012  Chandigarh  Kings XI Punjab
  339  340.0  Yes    2012  Chandigarh  Kings XI Punjab

                             team2                  toss_winner toss_decision  \
  45                 Gujarat Lions                Gujarat Lions         field
  47         Kolkata Knight Riders        Kolkata Knight Riders         field
  68                Mumbai Indians               Mumbai Indians         field
  80         Kolkata Knight Riders              Kings XI Punjab           bat
  96              Rajasthan Royals             Rajasthan Royals         field
  176             Delhi Daredevils             Delhi Daredevils         field
  204  Royal Challengers Bangalore              Kings XI Punjab           bat
  255             Rajasthan Royals             Rajasthan Royals         field
  283                Pune Warriors              Kings XI Punjab           bat
  286               Mumbai Indians               Mumbai Indians         field
  329        Kolkata Knight Riders              Kings XI Punjab           bat
  332  Royal Challengers Bangalore  Royal Challengers Bangalore         field
  339               Mumbai Indians              Kings XI Punjab           bat

       result  dl_applied                       winner
  45   normal         0.0                Gujarat Lions

In [24]:
dict(list(g1))

{('Ahmedabad',
  'Deccan Chargers'):         id date  season       city            team1             team2  \
 194  195.0  Yes    2010  Ahmedabad  Deccan Chargers  Rajasthan Royals

          toss_winner toss_decision  result  dl_applied            winner
 194  Deccan Chargers           bat  normal         0.0  Rajasthan Royals  ,
 ('Ahmedabad',
  'Rajasthan Royals'):         id date  season       city             team1                  team2  \
 179  180.0  Yes    2010  Ahmedabad  Rajasthan Royals       Delhi Daredevils
 186  187.0  Yes    2010  Ahmedabad  Rajasthan Royals  Kolkata Knight Riders
 197  198.0  Yes    2010  Ahmedabad  Rajasthan Royals    Chennai Super Kings

           toss_winner toss_decision  result  dl_applied            winner
 179  Delhi Daredevils         field  normal         0.0  Delhi Daredevils
 186  Rajasthan Royals           bat  normal         0.0  Rajasthan Royals
 197  Rajasthan Royals           bat  normal         0.0  Rajasthan Royals  ,
 ('Bangalore',
  'Chennai Super Kings'):         id date  season       city                team1  \
 73    74.0  Yes    2008  Bangalore  Chennai Super Kings
 301  302.0  Yes    2011  Bangalore  Chennai Super Kings

                            team2                  toss_winner toss_decision  \
 73   Royal Challengers Bangalore          Chennai Super Kings           bat
 301  Royal Challengers Bangalore  Royal Challengers Bangalore         field

      result  dl_applied                       winner
 73   normal         0.0          Chennai Super Kings
 301  normal         0.0  Royal Challengers Bangalore  ,
 ('Bangalore',
  'Deccan Chargers'):         id date  season       city            team1  \
 355  356.0   No    2012  Bangalore  Deccan Chargers

                            team2                  toss_winner toss_decision  \
 355  Royal Challengers Bangalore  Royal Challengers Bangalore         field

      result  dl_applied                       winner
 355  normal         0.0  Royal Challengers Bangalore  ,
 ('Bangalore',
  'Delhi Daredevils'):         id date  season       city             team1  \
 196  197.0  Yes    2010  Bangalore  Delhi Daredevils

                            team2                  toss_winner toss_decision  \
 196  Royal Challengers Bangalore  Royal Challengers Bangalore         field

      result  dl_applied            winner
 196  normal         0.0  Delhi Daredevils  ,
 ('Bangalore',
  'Kings XI Punjab'):         id date  season       city            team1  \
 41    42.0  Yes    2017  Bangalore  Kings XI Punjab
 180  181.0  Yes    2010  Bangalore  Kings XI Punjab

                            team2                  toss_winner toss_decision  \
 41   Royal Challengers Bangalore  Royal Challengers Bangalore         field
 180  Royal Challengers Bangalore              Kings XI Punjab           bat

      result  dl_applied                       winner
 41   normal         0.0              Kings XI Punjab
 180  normal         0.0  Royal Challengers Bangalore  ,
 ('Bangalore',
  'Kochi Tuskers Kerala'):         id date  season       city                 team1  \
 282  283.0  Yes    2011  Bangalore  Kochi Tuskers Kerala

                            team2           toss_winner toss_decision  result  \
 282  Royal Challengers Bangalore  Kochi Tuskers Kerala           bat  normal

      dl_applied                       winner
 282         0.0  Royal Challengers Bangalore  ,
 ('Bangalore',
  'Kolkata Knight Riders'):         id date  season       city                  team1  \
 57    58.0  Yes    2017  Bangalore  Kolkata Knight Riders
 59    60.0  Yes    2008  Bangalore  Kolkata Knight Riders
 216  217.0  Yes    2010  Bangalore  Kolkata Knight Riders
 290  291.0  Yes    2011  Bangalore  Kolkata Knight Riders
 316  317.0  Yes    2012  Bangalore  Kolkata Knight Riders

                            team2                  toss_winner toss_decision  \
 57                Mumbai Indians               Mumbai Indians         field
 59   Royal Challengers Bangalore  Royal Challengers Bangalore         field
 216  Royal Challengers Bangalore  Royal Challengers Bangalore         field
 290  Royal Challengers Bangalore  Royal Challengers Bangalore         field
 316  Royal Challengers Bangalore  Royal Challengers Bangalore         field

      result  dl_applied                       winner
 57   normal         0.0               Mumbai Indians
 59   normal         0.0        Kolkata Knight Riders
 216  normal         0.0  Royal Challengers Bangalore
 290  normal         1.0  Royal Challengers Bangalore
 316  normal         0.0        Kolkata Knight Riders  ,
 ('Bangalore',
  'Mumbai Indians'):         id date  season       city           team1  \
 225  226.0  Yes    2010  Bangalore  Mumbai Indians

                            team2                  toss_winner toss_decision  \
 225  Royal Challengers Bangalore  Royal Challengers Bangalore         field

      result  dl_applied          winner
 225  normal         0.0  Mumbai Indians  ,
 ('Bangalore',
  'Pune Warriors'):         id date  season       city          team1  \
 328  329.0  Yes    2012  Bangalore  Pune Warriors

                            team2    toss_winner toss_decision  result  \
 328  Royal Challengers Bangalore  Pune Warriors           bat  normal

      dl_applied                       winner
 328         0.0  Royal Challengers Bangalore  ,
 ('Bangalore',
  'Rajasthan Royals'):         id date  season       city             team1  \
 183  184.0  Yes    2010  Bangalore  Rajasthan Royals
 325  326.0  Yes    2012  Bangalore  Rajasthan Royals

                            team2                  toss_winner toss_decision  \
 183  Royal Challengers Bangalore  Royal Challengers Bangalore         field
 325  Royal Challengers Bangalore             Rajasthan Royals           bat

      result  dl_applied                       winner
 183  normal         0.0  Royal Challengers Bangalore
 325  normal         0.0             Rajasthan Royals  ,
 ('Bangalore',
  'Rising Pune Supergiant'):       id date  season       city                   team1  \
 16  17.0  Yes    2017  Bangalore  Rising Pune Supergiant

                           team2                  toss_winner toss_decision  \
 16  Royal Challengers Bangalore  Royal Challengers Bangalore         field

     result  dl_applied                  winner
 16  normal         0.0  Rising Pune Supergiant  ,
 ('Bangalore',
  'Royal Challengers Bangalore'):         id date  season       city                        team1  \
 11    12.0  Yes    2017  Bangalore  Royal Challengers Bangalore
 29    30.0  Yes    2017  Bangalore  Royal Challengers Bangalore
 44    45.0  Yes    2017  Bangalore  Royal Challengers Bangalore
 69    70.0  Yes    2008  Bangalore  Royal Challengers Bangalore
 83    84.0  Yes    2008  Bangalore  Royal Challengers Bangalore
 89    90.0  Yes    2008  Bangalore  Royal Challengers Bangalore
 103  104.0  Yes    2008  Bangalore  Royal Challengers Bangalore
 110  111.0  Yes    2008  Bangalore  Royal Challengers Bangalore
 191  192.0  Yes    2010  Bangalore  Royal Challengers Bangalore
 213  214.0  Yes    2010  Bangalore  Royal Challengers Bangalore
 241  242.0  Yes    2011  Bangalore  Royal Challengers Bangalore
 267  268.0  Yes    2011  Bangalore  Royal Challengers Bangalore
 279  280.0  Yes    2011  Bangalore  Royal Challengers Bangalore
 311  312.0  Yes    2012  Bangalore  Royal Challengers Bangalore
 349  350.0  Yes    2012  Bangalore  Royal Challengers Bangalore
 366  367.0   No    2012  Bangalore  Royal Challengers Bangalore

                      team2            toss_winner toss_decision  result  \
 11          Mumbai Indians         Mumbai Indians         field  normal
 29           Gujarat Lions          Gujarat Lions         field  normal
 44   Kolkata Knight Riders  Kolkata Knight Riders         field  normal
 69        Rajasthan Royals       Rajasthan Royals         field  normal
 83         Kings XI Punjab        Kings XI Punjab         field  normal
 89          Mumbai Indians         Mumbai Indians         field  normal
 103       Delhi Daredevils       Delhi Daredevils         field  normal
 110        Deccan Chargers        Deccan Chargers         field  normal
 191    Chennai Super Kings    Chennai Super Kings         field  normal
 213        Deccan Chargers        Deccan Chargers         field  normal
 241         Mumbai Indians         Mumbai Indians         field  normal
 267          Pune Warriors          Pune Warriors         field  normal
 279        Kings XI Punjab        Kings XI Punjab         field  normal
 311       Delhi Daredevils       Delhi Daredevils         field  normal
 349        Kings XI Punjab        Kings XI Punjab         field  normal
 366         Mumbai Indians         Mumbai Indians         field  normal

      dl_applied                       winner
 11          NaN               Mumbai Indians
 29          0.0                Gujarat Lions
 44          0.0        Kolkata Knight Riders
 69          0.0             Rajasthan Royals
 83          0.0              Kings XI Punjab
 89          0.0               Mumbai Indians
 103         0.0             Delhi Daredevils
 110         0.0  Royal Challengers Bangalore
 191         0.0  Royal Challengers Bangalore
 213         0.0              Deccan Chargers
 241         0.0               Mumbai Indians
 267         0.0  Royal Challengers Bangalore
 279         0.0  Royal Challengers Bangalore
 311         0.0  Royal Challengers Bangalore
 349         0.0              Kings XI Punjab
 366         0.0               Mumbai Indians  ,
 ('Bangalore',
  'Sunrisers Hyderabad'):       id date  season       city                team1                  team2  \
 56  57.0  Yes    2017  Bangalore  Sunrisers Hyderabad  Kolkata Knight Riders

               toss_winner toss_decision  result  dl_applied  \
 56  Kolkata Knight Riders         field  normal         1.0

                    winner
 56  Kolkata Knight Riders  ,
 ('Bloemfontein',
  'Delhi Daredevils'):         id date  season          city             team1             team2  \
 160  161.0  Yes    2009  Bloemfontein  Delhi Daredevils   Kings XI Punjab
 164  165.0  Yes    2009  Bloemfontein  Delhi Daredevils  Rajasthan Royals

           toss_winner toss_decision  result  dl_applied            winner
 160   Kings XI Punjab         field  normal         0.0   Kings XI Punjab
 164  Delhi Daredevils           bat  normal         0.0  Delhi Daredevils  ,
 ('Cape Town',
  'Deccan Chargers'):         id date  season       city            team1  \
 123  124.0  Yes    2009  Cape Town  Deccan Chargers

                            team2      toss_winner toss_decision  result  \
 123  Royal Challengers Bangalore  Deccan Chargers           bat  normal

      dl_applied           winner
 123         0.0  Deccan Chargers  ,
 ('Cape Town',
  'Kings XI Punjab'):         id date  season       city            team1             team2  \
 119  120.0  Yes    2009  Cape Town  Kings XI Punjab  Delhi Daredevils
 129  130.0  Yes    2009  Cape Town  Kings XI Punjab  Rajasthan Royals

           toss_winner toss_decision  result  dl_applied            winner
 119  Delhi Daredevils         field  normal         1.0  Delhi Daredevils
 129   Kings XI Punjab           bat  normal         0.0   Kings XI Punjab  ,
 ('Cape Town',
  'Kolkata Knight Riders'):         id date  season       city                  team1            team2  \
 120  121.0  Yes    2009  Cape Town  Kolkata Knight Riders  Deccan Chargers

                toss_winner toss_decision  result  dl_applied           winner
 120  Kolkata Knight Riders           bat  normal         0.0  Deccan Chargers  ,
 ('Cape Town',
  'Mumbai Indians'):         id date  season       city           team1                team2  \
 117  118.0  Yes    2009  Cape Town  Mumbai Indians  Chennai Super Kings

              toss_winner toss_decision  result  dl_applied          winner
 117  Chennai Super Kings         field  normal         0.0  Mumbai Indians  ,
 ('Cape Town',
  'Rajasthan Royals'):         id date  season       city             team1                  team2  \
 125  126.0  Yes    2009  Cape Town  Rajasthan Royals  Kolkata Knight Riders

                toss_winner toss_decision result  dl_applied            winner
 125  Kolkata Knight Riders         field    tie         0.0  Rajasthan Royals  ,
 ('Cape Town',
  'Royal Challengers Bangalore'):         id date  season       city                        team1  \
 118  119.0  Yes    2009  Cape Town  Royal Challengers Bangalore

                 team2                  toss_winner toss_decision  result  \
 118  Rajasthan Royals  Royal Challengers Bangalore           bat  normal

      dl_applied                       winner
 118         0.0  Royal Challengers Bangalore  ,
 ('Centurion',
  'Chennai Super Kings'):         id date  season       city                team1  \
 136  137.0  Yes    2009  Centurion  Chennai Super Kings
 148  149.0  Yes    2009  Centurion  Chennai Super Kings
 165  166.0  Yes    2009  Centurion  Chennai Super Kings

                      team2          toss_winner toss_decision  result  \
 136       Rajasthan Royals     Rajasthan Royals         field  normal
 148        Kings XI Punjab  Chennai Super Kings           bat  normal
 165  Kolkata Knight Riders  Chennai Super Kings           bat  normal

      dl_applied                 winner
 136         0.0    Chennai Super Kings
 148         1.0    Chennai Super Kings
 165         0.0  Kolkata Knight Riders  ,
 ('Centurion',
  'Deccan Chargers'):         id date  season       city            team1             team2  \
 135  136.0  Yes    2009  Centurion  Deccan Chargers  Delhi Daredevils
 146  147.0  Yes    2009  Centurion  Deccan Chargers    Mumbai Indians

           toss_winner toss_decision  result  dl_applied            winner
 135  Delhi Daredevils         field  normal         0.0  Delhi Daredevils
 146   Deccan Chargers           bat  normal         0.0   Deccan Chargers  ,
 ('Centurion',
  'Delhi Daredevils'):         id date  season       city             team1             team2  \
 132  133.0  Yes    2009  Centurion  Delhi Daredevils  Rajasthan Royals
 171  172.0  Yes    2009  Centurion  Delhi Daredevils   Deccan Chargers

           toss_winner toss_decision  result  dl_applied            winner
 132  Delhi Daredevils           bat  normal         0.0  Rajasthan Royals
 171   Deccan Chargers         field  normal         0.0   Deccan Chargers  ,
 ('Centurion',
  'Kings XI Punjab'):         id date  season       city            team1           team2  \
 156  157.0  Yes    2009  Centurion  Kings XI Punjab  Mumbai Indians

          toss_winner toss_decision  result  dl_applied          winner
 156  Kings XI Punjab           bat  normal         0.0  Mumbai Indians  ,
 ('Centurion',
  'Kolkata Knight Riders'):         id date  season       city                  team1  \
 155  156.0  Yes    2009  Centurion  Kolkata Knight Riders

                            team2                  toss_winner toss_decision  \
 155  Royal Challengers Bangalore  Royal Challengers Bangalore         field

      result  dl_applied                       winner
 155  normal         0.0  Royal Challengers Bangalore  ,
 ('Centurion',
  'Mumbai Indians'):         id date  season       city           team1             team2  \
 169  170.0  Yes    2009  Centurion  Mumbai Indians  Delhi Daredevils

           toss_winner toss_decision  result  dl_applied            winner
 169  Delhi Daredevils         field  normal         0.0  Delhi Daredevils  ,
 ('Centurion',
  'Royal Challengers Bangalore'):         id date  season       city                        team1  \
 147  148.0  Yes    2009  Centurion  Royal Challengers Bangalore
 170  171.0  Yes    2009  Centurion  Royal Challengers Bangalore

                 team2                  toss_winner toss_decision  result  \
 147  Rajasthan Royals             Rajasthan Royals         field  normal
 170   Deccan Chargers  Royal Challengers Bangalore           bat  normal

      dl_applied                       winner
 147         0.0             Rajasthan Royals
 170         0.0  Royal Challengers Bangalore  ,
 ('Chandigarh',
  'Chennai Super Kings'):         id date  season        city                team1            team2  \
 60    61.0  Yes    2008  Chandigarh  Chennai Super Kings  Kings XI Punjab
 242  243.0  Yes    2011  Chandigarh  Chennai Super Kings  Kings XI Punjab

              toss_winner toss_decision  result  dl_applied  \
 60   Chennai Super Kings           bat  normal         0.0
 242      Kings XI Punjab         field  normal         0.0

                   winner
 60   Chennai Super Kings
 242      Kings XI Punjab  ,
 ('Chandigarh',
  'Deccan Chargers'):         id date  season        city            team1            team2  \
 107  108.0  Yes    2008  Chandigarh  Deccan Chargers  Kings XI Punjab
 365  366.0   No    2012  Chandigarh  Deccan Chargers  Kings XI Punjab

          toss_winner toss_decision  result  dl_applied           winner
 107  Kings XI Punjab         field  normal         0.0  Kings XI Punjab
 365  Deccan Chargers           bat  normal         0.0  Kings XI Punjab  ,
 ('Chandigarh',
  'Delhi Daredevils'):       id date  season        city             team1            team2  \
 34  35.0  Yes    2017  Chandigarh  Delhi Daredevils  Kings XI Punjab
 72  73.0  Yes    2008  Chandigarh  Delhi Daredevils  Kings XI Punjab

          toss_winner toss_decision  result  dl_applied           winner
 34   Kings XI Punjab         field  normal         0.0  Kings XI Punjab
 72  Delhi Daredevils           bat  normal         0.0  Kings XI Punjab  ,
 ('Chandigarh',
  'Kings XI Punjab'):         id date  season        city            team1  \
 45    46.0  Yes    2017  Chandigarh  Kings XI Punjab
 47    48.0  Yes    2017  Chandigarh  Kings XI Punjab
 68    69.0  Yes    2008  Chandigarh  Kings XI Punjab
 80    81.0  Yes    2008  Chandigarh  Kings XI Punjab
 96    97.0  Yes    2008  Chandigarh  Kings XI Punjab
 176  177.0  Yes    2010  Chandigarh  Kings XI Punjab
 204  205.0  Yes    2010  Chandigarh  Kings XI Punjab
 255  256.0  Yes    2011  Chandigarh  Kings XI Punjab
 283  284.0  Yes    2011  Chandigarh  Kings XI Punjab
 286  287.0  Yes    2011  Chandigarh  Kings XI Punjab
 329  330.0  Yes    2012  Chandigarh  Kings XI Punjab
 332  333.0  Yes    2012  Chandigarh  Kings XI Punjab
 339  340.0  Yes    2012  Chandigarh  Kings XI Punjab

                            team2                  toss_winner toss_decision  \
 45                 Gujarat Lions                Gujarat Lions         field
 47         Kolkata Knight Riders        Kolkata Knight Riders         field
 68                Mumbai Indians               Mumbai Indians         field
 80         Kolkata Knight Riders              Kings XI Punjab           bat
 96              Rajasthan Royals             Rajasthan Royals         field
 176             Delhi Daredevils             Delhi Daredevils         field
 204  Royal Challengers Bangalore              Kings XI Punjab           bat
 255             Rajasthan Royals             Rajasthan Royals         field
 283                Pune Warriors              Kings XI Punjab           bat
 286               Mumbai Indians               Mumbai Indians         field
 329        Kolkata Knight Riders              Kings XI Punjab           bat
 332  Royal Challengers Bangalore  Royal Challengers Bangalore         field
 339               Mumbai Indians              Kings XI Punjab           bat

      result  dl_applied                       winner
 45   normal         0.0                Gujarat Lions
 47   normal         0.0              Kings XI Punjab
 68   normal         0.0              Kings XI Punjab
 80   normal         0.0              Kings XI Punjab
 96   normal         0.0              Kings XI Punjab
 176  normal         0.0             Delhi Daredevils
 204  normal         0.0  Royal Challengers Bangalore

In [25]:
data.groupby('city').get_group('Pune')

,id,date,season,city,team1,team2,toss_winner,toss_decision,result,dl_applied,winner
1,2.0,Yes,2017,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0.0,Rising Pune Supergiant
8,NaN,Yes,2017,Pune,NaN,NaN,Rising Pune Supergiant,field,NaN,NaN,Delhi Daredevils
24,25.0,Yes,2017,Pune,Sunrisers Hyderabad,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0.0,Rising Pune Supergiant
28,29.0,Yes,2017,Pune,Rising Pune Supergiant,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0.0,Kolkata Knight Riders
32,33.0,Yes,2017,Pune,Rising Pune Supergiant,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0.0,Rising Pune Supergiant
37,38.0,Yes,2017,Pune,Gujarat Lions,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0.0,Rising Pune Supergiant
53,54.0,Yes,2017,Pune,Kings XI Punjab,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0.0,Rising Pune Supergiant
314,315.0,Yes,2012,Pune,Pune Warriors,Kings XI Punjab,Pune Warriors,bat,normal,0.0,Pune Warriors
323,324.0,Yes,2012,Pune,Chennai Super Kings,Pune Warriors,Chennai Super Kings,bat,normal,0.0,Pune Warriors
338,339.0,Yes,2012,Pune,Pune Warriors,Delhi Daredevils,Pune Warriors,bat,normal,0.0,Delhi Daredevils
340,341.0,Yes,2012,Pune,Deccan Chargers,Pune Warriors,Deccan Chargers,bat,normal,0.0,Deccan Chargers
350,351.0,Yes,2012,Pune,Mumbai Indians,Pune Warriors,Mumbai Indians,bat,normal,0.0,Mumbai Indians
357,358.0,No,2012,Pune,Pune Warriors,Rajasthan Royals,Pune Warriors,bat,normal,0.0,Rajasthan Royals
361,362.0,No,2012,Pune,Royal Challengers Bangalore,Pune Warriors,Pune Warriors,field,normal,0.0,Royal Challengers Bangalore
374,375.0,No,2012,Pune,Kolkata Knight Riders,Pune Warriors,Kolkata Knight Riders,bat,normal,0.0,Kolkata Knight Riders
377,378.0,No,2012,Pune,Kolkata Knight Riders,Delhi Daredevils,Kolkata Knight Riders,bat,normal,0.0,Kolkata Knight Riders

In [26]:
data.groupby('team1').get_group('Pune Warriors')

,id,date,season,city,team1,team2,toss_winner,toss_decision,result,dl_applied,winner
249,250.0,Yes,2011,Mumbai,Pune Warriors,Delhi Daredevils,Delhi Daredevils,field,normal,0.0,Delhi Daredevils
253,254.0,Yes,2011,Mumbai,Pune Warriors,Mumbai Indians,Pune Warriors,bat,normal,0.0,Mumbai Indians
263,264.0,Yes,2011,Mumbai,Pune Warriors,Chennai Super Kings,Pune Warriors,bat,normal,0.0,Chennai Super Kings
270,271.0,Yes,2011,Jaipur,Pune Warriors,Rajasthan Royals,Rajasthan Royals,field,normal,0.0,Rajasthan Royals
294,295.0,Yes,2011,Mumbai,Pune Warriors,Deccan Chargers,Deccan Chargers,field,normal,0.0,Deccan Chargers
297,298.0,Yes,2011,Mumbai,Pune Warriors,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0.0,Kolkata Knight Riders
309,310.0,Yes,2012,Mumbai,Pune Warriors,Mumbai Indians,Mumbai Indians,field,normal,0.0,Pune Warriors
314,315.0,Yes,2012,Pune,Pune Warriors,Kings XI Punjab,Pune Warriors,bat,normal,0.0,Pune Warriors
320,321.0,Yes,2012,Chandigarh,Pune Warriors,Kings XI Punjab,Kings XI Punjab,field,normal,0.0,Kings XI Punjab
328,329.0,Yes,2012,Bangalore,Pune Warriors,Royal Challengers Bangalore,Pune Warriors,bat,normal,0.0,Royal Challengers Bangalore
334,335.0,Yes,2012,Delhi,Pune Warriors,Delhi Daredevils,Delhi Daredevils,field,normal,0.0,Pune Warriors
338,339.0,Yes,2012,Pune,Pune Warriors,Delhi Daredevils,Pune Warriors,bat,normal,0.0,Delhi Daredevils
357,358.0,No,2012,Pune,Pune Warriors,Rajasthan Royals,Pune Warriors,bat,normal,0.0,Rajasthan Royals

In [27]:
g1.sum()

                                              id  season  dl_applied
city          team1
Ahmedabad     Deccan Chargers              195.0    2010         0.0
              Rajasthan Royals             565.0    6030         0.0
Bangalore     Chennai Super Kings          376.0    4019         0.0
              Deccan Chargers              356.0    2012         0.0
              Delhi Daredevils             197.0    2010         0.0
...                                          ...     ...         ...
Rajkot        Kings XI Punjab               26.0    2017         0.0
              Rising Pune Supergiant        13.0    2017         0.0
              Royal Challengers Bangalore   20.0    2017         0.0
Visakhapatnam Chennai Super Kings          313.0    2012         0.0
              Deccan Chargers              316.0    2012         0.0

[147 rows x 3 columns]

In [28]:
g1.mean()

                                                   id  season  dl_applied
city          team1
Ahmedabad     Deccan Chargers              195.000000  2010.0         0.0
              Rajasthan Royals             188.333333  2010.0         0.0
Bangalore     Chennai Super Kings          188.000000  2009.5         0.0
              Deccan Chargers              356.000000  2012.0         0.0
              Delhi Daredevils             197.000000  2010.0         0.0
...                                               ...     ...         ...
Rajkot        Kings XI Punjab               26.000000  2017.0         0.0
              Rising Pune Supergiant        13.000000  2017.0         NaN
              Royal Challengers Bangalore   20.000000  2017.0         0.0
Visakhapatnam Chennai Super Kings          313.000000  2012.0         0.0
              Deccan Chargers              316.000000  2012.0         0.0

[147 rows x 3 columns]

In [29]:
g1.describe()

                                             id                          \
                                          count        mean         std
city          team1
Ahmedabad     Deccan Chargers               1.0  195.000000         NaN
              Rajasthan Royals              3.0  188.333333    9.073772
Bangalore     Chennai Super Kings           2.0  188.000000  161.220346
              Deccan Chargers               1.0  356.000000         NaN
              Delhi Daredevils              1.0  197.000000         NaN
...                                         ...         ...         ...
Rajkot        Kings XI Punjab               1.0   26.000000         NaN
              Rising Pune Supergiant        1.0   13.000000         NaN
              Royal Challengers Bangalore   1.0   20.000000         NaN
Visakhapatnam Chennai Super Kings           1.0  313.000000         NaN
              Deccan Chargers               1.0  316.000000         NaN

                                                                              \
                                             min    25%    50%    75%    max
city          team1
Ahmedabad     Deccan Chargers              195.0  195.0  195.0  195.0  195.0
              Rajasthan Royals             180.0  183.5  187.0  192.5  198.0
Bangalore     Chennai Super Kings           74.0  131.0  188.0  245.0  302.0
              Deccan Chargers              356.0  356.0  356.0  356.0  356.0
              Delhi Daredevils             197.0  197.0  197.0  197.0  197.0
...                                          ...    ...    ...    ...    ...
Rajkot        Kings XI Punjab               26.0   26.0   26.0   26.0   26.0
              Rising Pune Supergiant        13.0   13.0   13.0   13.0   13.0
              Royal Challengers Bangalore   20.0   20.0   20.0   20.0   20.0
Visakhapatnam Chennai Super Kings          313.0  313.0  313.0  313.0  313.0
              Deccan Chargers              316.0  316.0  316.0  316.0  316.0

                                          season          ...           \
                                           count    mean  ...      75%
city          team1                                       ...
Ahmedabad     Deccan Chargers                1.0  2010.0  ...  2010.00
              Rajasthan Royals               3.0  2010.0  ...  2010.00
Bangalore     Chennai Super Kings            2.0  2009.5  ...  2010.25
              Deccan Chargers                1.0  2012.0  ...  2012.00
              Delhi Daredevils               1.0  2010.0  ...  2010.00
...                                          ...     ...  ...      ...
Rajkot        Kings XI Punjab                1.0  2017.0  ...  2017.00
              Rising Pune Supergiant         1.0  2017.0  ...  2017.00
              Royal Challengers Bangalore    1.0  2017.0  ...  2017.00
Visakhapatnam Chennai Super Kings            1.0  2012.0  ...  2012.00
              Deccan Chargers                1.0  2012.0  ...  2012.00

                                                  dl_applied                 \
                                              max      count mean  std  min
city          team1
Ahmedabad     Deccan Chargers              2010.0        1.0  0.0  NaN  0.0
              Rajasthan Royals             2010.0        3.0  0.0  0.0  0.0
Bangalore     Chennai Super Kings          2011.0        2.0  0.0  0.0  0.0
              Deccan Chargers              2012.0        1.0  0.0  NaN  0.0
              Delhi Daredevils             2010.0        1.0  0.0  NaN  0.0
...                                           ...        ...  ...  ...  ...
Rajkot        Kings XI Punjab              2017.0        1.0  0.0  NaN  0.0
              Rising Pune Supergiant       2017.0        0.0  NaN  NaN  NaN
              Royal Challengers Bangalore  2017.0        1.0  0.0  NaN  0.0
Visakhapatnam Chennai Super Kings          2012.0        1.0  0.0  NaN  0.0
              Deccan Chargers              2012.0        1.0  0.0  NaN  0.0


                                           25%  50%  75%  max
city          team1
Ahmedabad     Deccan Chargers              0.0  0.0  0.0  0.0
              Rajasthan Royals             0.0  0.0  0.0  0.0
Bangalore     Chennai Super Kings          0.0  0.0  0.0  0.0
              Deccan Chargers              0.0  0.0  0.0  0.0
              Delhi Daredevils             0.0  0.0  0.0  0.0
...                                        ...  ...  ...  ...
Rajkot        Kings XI Punjab              0.0  0.0  0.0  0.0
              Rising Pune Supergiant       NaN  NaN  NaN  NaN
              Royal Challengers Bangalore  0.0  0.0  0.0  0.0
Visakhapatnam Chennai Super Kings          0.0  0.0  0.0  0.0
              Deccan Chargers              0.0  0.0  0.0  0.0

[147 rows x 24 columns]

In [30]:
g1.agg(['sum', 'max', 'mean'])

                                              id                    season  \
                                             sum    max        mean    sum
city          team1
Ahmedabad     Deccan Chargers              195.0  195.0  195.000000   2010
              Rajasthan Royals             565.0  198.0  188.333333   6030
Bangalore     Chennai Super Kings          376.0  302.0  188.000000   4019
              Deccan Chargers              356.0  356.0  356.000000   2012
              Delhi Daredevils             197.0  197.0  197.000000   2010
...                                          ...    ...         ...    ...
Rajkot        Kings XI Punjab               26.0   26.0   26.000000   2017
              Rising Pune Supergiant        13.0   13.0   13.000000   2017
              Royal Challengers Bangalore   20.0   20.0   20.000000   2017
Visakhapatnam Chennai Super Kings          313.0  313.0  313.000000   2012
              Deccan Chargers              316.0  316.0  316.000000   2012

                                                        dl_applied
                                            max    mean        sum  max mean
city          team1
Ahmedabad     Deccan Chargers              2010  2010.0        0.0  0.0  0.0
              Rajasthan Royals             2010  2010.0        0.0  0.0  0.0
Bangalore     Chennai Super Kings          2011  2009.5        0.0  0.0  0.0
              Deccan Chargers              2012  2012.0        0.0  0.0  0.0
              Delhi Daredevils             2010  2010.0        0.0  0.0  0.0
...                                         ...     ...        ...  ...  ...
Rajkot        Kings XI Punjab              2017  2017.0        0.0  0.0  0.0
              Rising Pune Supergiant       2017  2017.0        0.0  NaN  NaN
              Royal Challengers Bangalore  2017  2017.0        0.0  0.0  0.0
Visakhapatnam Chennai Super Kings          2012  2012.0        0.0  0.0  0.0
              Deccan Chargers              2012  2012.0        0.0  0.0  0.0

[147 rows x 9 columns]

# merge

### Pandas merge connects columns or indexes in DataFrame based on one or more keys.

In [31]:
data = pd.DataFrame({'ID' : [1,2,3,4],
                   'Class' : [9,10,11,12]})
data

   ID  Class
0   1      9
1   2     10
2   3     11
3   4     12

In [32]:
data1 = pd.DataFrame({'ID' : [1,2,3,4],
                   'Name' : ['A','B','C','D']})
data1

   ID Name
0   1    A
1   2    B
2   3    C
3   4    D

In [33]:
data2 = pd.DataFrame({'ID' : [1,2,3,5],
                   'Name' : ['A','B','C','D']})
data2

   ID Name
0   1    A
1   2    B
2   3    C
3   5    D

In [34]:
pd.merge(data, data1, on  = 'ID')

   ID  Class Name
0   1      9    A
1   2     10    B
2   3     11    C
3   4     12    D

In [35]:
pd.merge(data2, data, on  = 'ID')

   ID Name  Class
0   1    A      9
1   2    B     10
2   3    C     11

In [36]:
pd.merge(data2, data, on  = 'ID',how  = 'inner')

   ID Name  Class
0   1    A      9
1   2    B     10
2   3    C     11

In [37]:
pd.merge(data2, data, on  = 'ID',how = 'left')

   ID Name  Class
0   1    A    9.0
1   2    B   10.0
2   3    C   11.0
3   5    D    NaN

In [38]:
pd.merge(data2, data, on  = 'ID',how = 'right')

   ID Name  Class
0   1    A      9
1   2    B     10
2   3    C     11
3   4  NaN     12

In [39]:
pd.merge(data2, data, on  = 'ID',how = 'outer')

   ID Name  Class
0   1    A    9.0
1   2    B   10.0
2   3    C   11.0
3   5    D    NaN
4   4  NaN   12.0

In [40]:
pd.merge(data2, data, on  = 'ID',how = 'outer', indicator = True)

   ID Name  Class      _merge
0   1    A    9.0        both
1   2    B   10.0        both
2   3    C   11.0        both
3   5    D    NaN   left_only
4   4  NaN   12.0  right_only

In [41]:
data2 = pd.DataFrame({'ID' : [5,6,7,8],
                   'Name' : ['A','B','C','D']})
data2

   ID Name
0   5    A
1   6    B
2   7    C
3   8    D

In [42]:
data

   ID  Class
0   1      9
1   2     10
2   3     11
3   4     12

In [43]:
pd.merge(data, data2, left_index= True, right_index= True)

   ID_x  Class  ID_y Name
0     1      9     5    A
1     2     10     6    B
2     3     11     7    C
3     4     12     8    D

In [44]:
data3 = pd.DataFrame({'ID' : [5,6,7,8],
                   'Name' : ['A','B','C','D']})
data3

   ID Name
0   5    A
1   6    B
2   7    C
3   8    D

In [45]:
pd.merge(data2, data3, on = 'ID', suffixes= ('_data2','_data3'))

   ID Name_data2 Name_data3
0   5          A          A
1   6          B          B
2   7          C          C
3   8          D          D